[package]
name = "medical_record_management"
version = "1.0.0"
authors = []

[addresses]
MedicalRecordManagement = '0x2c1d9635d5455fa5f8673914b1606cc38160e8ed3d18f516d6619b7211740a6d'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]